name: CI (PR / main)

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.txt"
      - "LICENSE"
      - "docs/**"
  push:
    branches: [ "main" ]

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.1

      - name: pre-commit-c-lite
        uses: pre-commit-ci/lite-action@v1.1.0
        if: always()

  build:
    name: Build & Tests (Maven)
    runs-on: ubuntu-latest
    needs: [ pre-commit ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Build with Maven
        run: mvn --no-transfer-progress verify

  docker-build:
    name: Docker build (no push)
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      # ton Dockerfile attend target/webgoat-*.jar
      - name: Package jar (skip tests)
        run: mvn --no-transfer-progress -DskipTests clean package

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: webgoat-devsecops:ci
